### ISSUE TITLE
[FEAT] Emoji Avatars

### ISSUE THREAD

**Issue by JChamberlain28** [Team-5-Cyan-Camel/Flatmates#34]
Allow the user to select from a list of emoji's. This will be their avatar. It will be shown in various locations e.g. in the rosters, to personalize each users presence in the room.
- [ ] Backend support for storing an emoji, and updating it 
- [ ] Frontend emoji selection on registering
- [ ] Ability to change emoji after signup in frontend

**Comment by UltimaKuma** [comment]
Not implementing due to time constraints, but good for future work
