### ISSUE TITLE
[BUG] Failed Tests  

### ISSUE THREAD

**Issue by Esther561** [Team-5-Cyan-Camel/Flatmates#85]
Most tests in the backend are failed.

![image](https://user-images.githubusercontent.com/72179615/120914407-495aba00-c6f2-11eb-9522-f61a053fc6bd.png)

**Comment by JChamberlain28** [comment]
We would appreciate a more detailed bug report including your configuration. None of the developers have replicated this issue as such an issue would prevent us from releasing.

**Comment by JChamberlain28** [comment]
Please check you are using the .env files supplied. I just noticed an example.env in backend. This was not removed by us when it was supposed to. That is not the .env file.

**Comment by dikunong** [comment]
![image](https://user-images.githubusercontent.com/1442037/120920420-cac24480-c712-11eb-965d-580803063fc8.png)

Just confirming that they all pass when using the `.env` file Doris provided (which I completely forgot we were given, that's my bad).

I have an absolutely unconfirmed hunch that the tests may be dependent on some entries pre-existing in the database, which wouldn't be there if you were connected to a fresh MongoDB instance. For example, I noticed that the user login is not created in the tests, the tests just send a login request with that username and password, so if that user hadn't already been created every login attempt would fail. This is just a hunch based on me trying to run the tests with a fresh local instance of MongoDB and getting a lot of 401s. I could be totally wrong.

**Comment by JChamberlain28** [comment]
Nice investigating @dikunong. That is correct. Reflecting on this it would have been better to have the tests preconfigured these but the tests still helped us out in development well 🙂

**Comment by JChamberlain28** [comment]
We are quite reliant on atlas unfortunately

**Comment by JChamberlain28** [comment]
@Esther561 feel free to open this issue again if you were unable to resolve the issue with @dikunong solution
